import Head from 'next/head';
import { Navbar } from '@ui';

export const RootLayout: React.FC<{ children: JSX.Element | JSX.Element[], send?: boolean }> = ({ children, send = false }) => {
  return (
    <>
      <Head>
        <title>Poke-Vote</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-blue-600 h-screen'>
        <Navbar />

        <div>
          {children}
        </div>
      </main>
    </>
  )
};

